apiVersion: v1
kind: Service
metadata:
  name: redis
  labels: 
    app: redis-service
    type: demo
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
     app: web
     type: redis

