apiVersion: v1
kind: Service
metadata:
  name: result
  labels: 
    app: result-service
    type: demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web
    type: result

