apiVersion: v1
kind: Service
metadata:
  name: voting
  labels: 
    app: voting-service
    type: demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
      app: web
      type: voting
