apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: my-app
    type: web
spec:
  selector:
    matchLabels:
      type: web
  replicas: 3
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        type: web
    spec:
      containers:
        - image:  nginx
          name:  my-image

      